name = "books-api"
main = "src/worker.js"
compatibility_date = "2024-11-01"

[[durable_objects.bindings]]
name = "BOOKS"
class_name = "BookDurableObject"

[[durable_objects.bindings]]
name = "BOOK_INDEX"
class_name = "BookIndexDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["BookDurableObject", "BookIndexDurableObject"]
